tmp_dir: "/tmp/worker"
test:
  credentials:
    gcp: "/etc/credentials/gcp.json"
http:
  port: 8080
kubernetes:
  configPath: "/root/.kube/config"
  helm:
    debug: true
plugins:
  location: "/etc/athmos/plugins"
  crossplane:
    registry:
      address: "http://chart-museum:8080"
      username: "athmos"
      password: "athmos"
    gcp:
      firewall:
        chart: "gcp-firewall"
        version: "0.1.0"
      network:
        chart: "gcp-network"
        version: "0.1.0"
      provider:
        chart: "gcp-provider"
        version: "0.1.0"
      subnet:
        chart: "gcp-subnetwork"
        version: "0.1.0"
      vm:
        chart: "gcp-vm"
        version: "0.1.0"
      vpc:
        chart: "gcp-vpc"
        version: "0.1.0"
queue:
  uri: "amqp://user:password@rabbitmq:5672/"
  exchange: "from-infra-worker"
  queue: "to-infra-worker"
mongo:
  address: "mongodb"
  port: 27017
  username: "admin"
  password: "password"
  database: "plugin-db"
  projectCollection: "projects"
postgres:
  address: "postgres"
  port: 5432
  username: "postgres"
  password: "password"
  database: "plugin-db"


