tmpDir: "/tmp/worker"
staticFilesDir: "/static"
test:
  credentials:
    gcp: "/etc/credentials/resource.json"
http:
  port: 8081
kubernetes:
  configPath: "/root/.kube/config"
rabbitmq:
  uri: "amqp://user:password@rabbitmq:5672/"
  outcoming: "to-gateway-api"
  incoming: "to-infra-worker"
mongo:
  address: "mongodb"
  port: 27017
  username: "admin"
  password: "password"
  database: "plugin-db"
  projectCollection: "projects"
