staticFilesDir: "/static"
http:
  port: 8081
kubernetes:
  configPath: "/root/.kube/config"
rabbitmq:
  uri: "" #amqp://user:password@rabbitmq:5672/"
  address: "rabbitmq"
  port: 5672
  username: "user"
  password: "password"
  outcoming: "to-gateway-api"
  incoming: "to-infra-worker"
mongo:
  address: "mongodb"
  port: 27017
  username: "admin"
  password: "password"
  database: "plugin-db"
  projectCollection: "projects"
